"""Category definitions mapped from PRICE LIST.doc section headers."""

CATALOG_CATEGORIES = [
    ('PPR C Fittings', 'PPR'),
    ('Concealed Stop Cocks', 'CSC'),
    ('Gate Valves', 'GVL'),
    ('Flexible Tubes', 'FTB'),
    ('PVC Waste Fittings - Metro', 'PWM'),
    ('PVC Waste Fittings - Hari', 'PWH'),
    ('Aluminium Grating', 'AGR'),
    ('Bottle Traps', 'BTR'),
    ('Wastes', 'WST'),
    ('Floor Traps', 'FTR'),
    ('Appliances', 'APP'),
    ('G.I. Pipes', 'GIP'),
    ('PVC Pipes (Pressure)', 'PVC'),
    ('PVC Fittings (Pressure)', 'PVF'),
    ('PVC Waste Pipes', 'PWP'),
    ('Taps & Valves', 'TVL'),
    ('G.I. Fittings', 'GIF'),
    ('Pumps', 'PMP'),
    ('Shower Mixers', 'SMX'),
    ('Kitchen Sink Mixers', 'KSM'),
    ('Basin Mixers', 'BSM'),
    ('Tangit', 'TAN'),
    ('Seat Covers', 'SCV'),
    ('Pipes', 'PP'),
    ('Taps', 'TAP'),
    ('Sinks', 'SNK'),
    ('Toilet Bowls', 'TB'),
    ('Accessories', 'ACC'),
]

SECTION_TO_CATEGORY = {
    'PPR C FITTINGS': 'PPR C Fittings',
    'CONCEALED STOP COCKS (CROME)': 'Concealed Stop Cocks',
    'GATE VALVES': 'Gate Valves',
    'FLEXIBLE TUBES': 'Flexible Tubes',
    'PVC WASTE FITTINGS - METRO': 'PVC Waste Fittings - Metro',
    'PVC WASTE FITTINGS - HARI': 'PVC Waste Fittings - Hari',
    'ALLUMINIUM GRATING': 'Aluminium Grating',
    'BOTTLE TRAPS': 'Bottle Traps',
    'WASTES': 'Wastes',
    'FLOOR TRAPS': 'Floor Traps',
    'APPLIANCES': 'Appliances',
    'G.I. PIPES': 'G.I. Pipes',
    'PVC PIPES ( PRESSURE )': 'PVC Pipes (Pressure)',
    'PVC PIPES (PRESSURE)': 'PVC Pipes (Pressure)',
    'PVC FITTINGS ( PRESSURE)': 'PVC Fittings (Pressure)',
    'PVC FITTINGS (PRESSURE)': 'PVC Fittings (Pressure)',
    'PVC WASTE PIPES': 'PVC Waste Pipes',
    'TAPS & VALVES': 'Taps & Valves',
    'G.I. FITTINGS': 'G.I. Fittings',
    'PEDROLLO PUMP 0.5KW': 'Pumps',
    'SHOWER MIXERS': 'Shower Mixers',
    'KITCHEN SINK MIXER': 'Kitchen Sink Mixers',
    'BASIN MIXER': 'Basin Mixers',
    'TANGIT': 'Tangit',
    'SEAT COVER': 'Seat Covers',
}

TOP_LEVEL_HEADERS = set(SECTION_TO_CATEGORY.keys())

SUBSECTION_HEADERS = {
    'PPR ELBOWS', 'PPR REDUCERS', 'PPR TEES', 'PPR SOCKETS', 'PPR ADAPTORS', 'PPR UNIONS',
    'BENDS', 'TEE', 'PLUGS', 'BOSS CONNECTORS', 'W.C. CONNECTORS', 'VENT COWL (PVC)',
    'W.H. BASINS', 'W.C. PANS / CISTERNS', 'KITCHEN SINKS',
    'PVC ELBOWS', 'PVC TEE ( PRESSURE)', 'PVC VALVE SOCKETS (PRESSURE)', 'PVC REDUCERS ( PRESSURE)',
    'BIP TAPS (wall)', 'PILLAR TAPS (CHROME)', 'ANGLE VALVES', 'BALL COCKS', 'BALL VALVES', 'SPOUT TAPS',
    'G.I. UNIONS', 'G.I. BEND', 'G.I ELBOWS', 'G.I TEES', 'G.I SOCKETS', 'G.I. NIPPLES', 'SOCKETS',
    'G.I. REDUCING BUSH(SOCKETS)', 'G.I. PLUGS', 'G.I LONG THREAD NIPPLE', 'G.I BACK NUTS',
    'FOOT VALVES', 'NON RETURN VALVES',
}
